[env:m5stack-atoms3]
platform = espressif32
board = m5stack-atoms3
framework = arduino

monitor_speed = 115200
upload_speed = 1500000

board_build.partitions = min_spiffs.csv

extra_scripts = scripts/version.py

lib_deps =
    m5stack/M5Unified @ ^0.2.2
    bblanchon/ArduinoJson @ ^7.3.1

build_flags =
    -DCORE_DEBUG_LEVEL=0
